CREATE TABLE IF NOT EXISTS person(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullName text NOT NULL,
    birthDate date NOT NULL,
    father integer 
    mother integer 
)

INSERT INTO person(fullName,birthDate,father,mother)
    VALUES('Irma Franco','1952-12-15');
INSERT INTO person(fullName,birthDate, father, mother)
    VALUES('Jose Velasquez','1950-02-24');
INSERT INTO person(fullName,birthDate, father, mother)
    VALUES('Juan Velasquez','1992-03-14','2','1');